name = "dand-api"
main = "src/index.ts"
compatibility_date = "2024-04-24"
usage_model = "unbound"

[vars]
SESSION_SECRET = "3qP7hY9j!mR$ZwL6xV^tBnE@u8#KdF%o2pQjG0lHcXyTnVzAwRb6D$Pq7Jf9U#xM"
R2_ACCOUNT_ID = "edb46553918099e1a8b6d3f57f08de54"
R2_ACCESS_KEY_ID = "9b8493e86404b188f4ef94e0aad27980"
R2_SECRET_ACCESS_KEY = "b9fec9ef9874272562d7d83f48b91509decfb27489fdba6a776f7e6ffa6affaf"

[[d1_databases]]
binding = "MAPS_DB"
database_name = "maps-db"
database_id = "042c8ce4-9fd5-4670-94f3-ba91eda4fa36"

[[r2_buckets]]
binding = "MAPS_BUCKET"
bucket_name = "maps-bucket"
preview_bucket_name = "maps-bucket-preview"

[[durable_objects.bindings]]
name = "SESSION_HUB"
class_name = "SessionHub"
script_name = "session-do"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
