name = "dand-api"
main = "src/index.ts"
compatibility_date = "2024-04-24"
usage_model = "unbound"

[vars]
SESSION_SECRET = "3qP7hY9j!mR$ZwL6xV^tBnE@u8#KdF%o2pQjG0lHcXyTnVzAwRb6D$Pq7Jf9U#xM"
R2_ACCOUNT_ID = "00000000000000000000000000000000"
R2_ACCESS_KEY_ID = "YOUR_R2_ACCESS_KEY_ID"
R2_SECRET_ACCESS_KEY = "YOUR_R2_SECRET_ACCESS_KEY"

[[d1_databases]]
binding = "MAPS_DB"
database_name = "maps-db"
database_id = "042c8ce4-9fd5-4670-94f3-ba91eda4fa36"

[[r2_buckets]]
binding = "MAPS_BUCKET"
bucket_name = "maps-bucket"
preview_bucket_name = "maps-bucket-preview"

[[durable_objects.bindings]]
name = "SESSION_HUB"
class_name = "SessionHub"
script_name = "session-do"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
